# Generated by Django 5.1.5 on 2025-02-01 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle')], max_length=20)),
                ('starting_weight', models.FloatField(blank=True, help_text='Initial weight for weight goals', null=True)),
                ('target_value', models.FloatField(help_text='Target weight (kg) / lifting goal (kg)')),
                ('current_progress', models.FloatField(default=0.0, help_text='Progressed weight (Current weight)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
