# Generated by Django 5.1.5 on 2025-02-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessgoal',
            name='starting_weight',
        ),
    ]
