# Generated by Django 5.1.5 on 2025-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_fitnessgoal_current_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessgoal',
            name='starting_weight',
            field=models.FloatField(default=0.0, help_text='Starting weight (kg) or lifting progress (kg)'),
            preserve_default=False,
        ),
    ]
