# Generated by Django 5.1.5 on 2025-02-01 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_fitnessgoal_starting_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessgoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='FitnessGoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress_value', models.FloatField(help_text="User's progress at this point in time")),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='tracking.fitnessgoal')),
            ],
        ),
    ]
